## Exercise 00. Load and save

read_csv:

Filter the rows with index 2 and 3 using the skiprows argument. We know that these observations were fake.
Filter the last two rows from the footer using the skipfooter argument. We know that these observations were fake, too.
Assign the following names to the columns: datetime, user.
Use datetime as the index column.

In [ ]:
import pandas as pd 

df = pd.read_csv('../data/feed-views.log',
                    header=None, 
                    names=['temp'],
                    skiprows=[2,3],
                    skipfooter=2,
                    engine='python',
                    )
df[['datetime', 'user']]=df['temp'].str.split('\t', n=1, expand=True)
df=df.drop(columns=['temp'])
df['datetime']=pd.to_datetime(df['datetime'], )
df.set_index('datetime', inplace=True)
df

                                 user
datetime
2020-04-17 12:01:08.463179      artem
2020-04-17 12:01:23.743946      artem
2020-04-17 12:35:52.735016      artem
2020-04-17 12:36:21.401412     oksana
2020-04-17 12:36:22.023355     oksana
...                               ...
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel

[1072 rows x 1 columns]

In [ ]:
df.head()

In [ ]:
df.tail()

In [13]:
df.index.rename('data_time')
df

                                 user
datetime
2020-04-17 12:01:08.463179      artem
2020-04-17 12:01:23.743946      artem
2020-04-17 12:35:52.735016      artem
2020-04-17 12:36:21.401412     oksana
2020-04-17 12:36:22.023355     oksana
...                               ...
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel

[1072 rows x 1 columns]

to_csv:

Use ’;’ as the delimiter.
Save it to a file named feed-views-semicolon.log.

In [ ]:
df.to_csv('../data/feed-views-semicolon.log',sep=';',encoding='utf-8')