## Exercise 01

In [ ]:
import pandas as pd

views = pd.read_csv('../data/feed-views.log',
                    header=None, 
                    names=['temp'],
                    )
views[['datetime', 'user']]=views['temp'].str.split('\t', n=1, expand=True)
views=views.drop(columns=['temp'])
views['datetime']=pd.to_datetime(views['datetime'], )
views

                       datetime       user
0    2020-04-17 12:01:08.463179      artem
1    2020-04-17 12:01:23.743946      artem
2    2020-04-17 12:27:30.646665      artem
3    2020-04-17 12:35:44.884757      artem
4    2020-04-17 12:35:52.735016      artem
...                         ...        ...
1071 2020-05-21 18:45:20.441142  valentina
1072 2020-05-21 23:03:06.457819      maxim
1073 2020-05-21 23:23:49.995349      pavel
1074 2020-05-21 23:49:22.386789      artem
1075 2020-05-22 10:36:14.662600      artem

[1076 rows x 2 columns]

In [6]:
views.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1076 entries, 0 to 1075
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   datetime  1076 non-null   datetime64[ns]
 1   user      1076 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 16.9+ KB

In [7]:
views['year']=views['datetime'].dt.year
views['month']=views['datetime'].dt.month
views['day']=views['datetime'].dt.day
views['hour']=views['datetime'].dt.hour
views['minute']=views['datetime'].dt.minute
views['second']=views['datetime'].dt.second
views

,datetime,user,year,month,day,hour,minute,second
0,2020-04-17 12:01:08.463179,artem,2020,4,17,12,1,8
1,2020-04-17 12:01:23.743946,artem,2020,4,17,12,1,23
2,2020-04-17 12:27:30.646665,artem,2020,4,17,12,27,30
3,2020-04-17 12:35:44.884757,artem,2020,4,17,12,35,44
4,2020-04-17 12:35:52.735016,artem,2020,4,17,12,35,52
...,...,...,...,...,...,...,...,...
1071,2020-05-21 18:45:20.441142,valentina,2020,5,21,18,45,20
1072,2020-05-21 23:03:06.457819,maxim,2020,5,21,23,3,6
1073,2020-05-21 23:23:49.995349,pavel,2020,5,21,23,23,49
1074,2020-05-21 23:49:22.386789,artem,2020,5,21,23,49,22
1075,2020-05-22 10:36:14.662600,artem,2020,5,22,10,36,14

In [8]:

views['daytime']=pd.cut(views['hour'], bins=[-1,3,6,10,16,19,23], labels=['night','early morning', 'morning','afternoon', 'early evening','evening'])
views.set_index('user', inplace=True)
views

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
artem,2020-04-17 12:01:08.463179,2020,4,17,12,1,8,afternoon
artem,2020-04-17 12:01:23.743946,2020,4,17,12,1,23,afternoon
artem,2020-04-17 12:27:30.646665,2020,4,17,12,27,30,afternoon
artem,2020-04-17 12:35:44.884757,2020,4,17,12,35,44,afternoon
artem,2020-04-17 12:35:52.735016,2020,4,17,12,35,52,afternoon
...,...,...,...,...,...,...,...,...
valentina,2020-05-21 18:45:20.441142,2020,5,21,18,45,20,early evening
maxim,2020-05-21 23:03:06.457819,2020,5,21,23,3,6,evening
pavel,2020-05-21 23:23:49.995349,2020,5,21,23,23,49,evening
artem,2020-05-21 23:49:22.386789,2020,5,21,23,49,22,evening
artem,2020-05-22 10:36:14.662600,2020,5,22,10,36,14,morning

Calculate the number of elements in your dataframe.

Use the method count().
Calculate the number of elements in each time-of-day category using the value_counts() method.

In [9]:
views.count()

datetime    1076
year        1076
month       1076
day         1076
hour        1076
minute      1076
second      1076
daytime     1076
dtype: int64

In [10]:
views['daytime'].value_counts()

daytime
evening          509
afternoon        252
early evening    145
night            129
morning           36
early morning      5
Name: count, dtype: int64

Sort the values in your dataframe by hour, minute, and second in ascending order simultaneously, not one by one.

In [11]:
views_sorted=views.sort_values(by=['hour', 'minute', 'second'])
views_sorted

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
valentina,2020-05-15 00:00:13.222265,2020,5,15,0,0,13,night
valentina,2020-05-15 00:01:05.153738,2020,5,15,0,1,5,night
pavel,2020-05-12 00:01:27.764025,2020,5,12,0,1,27,night
pavel,2020-05-12 00:01:38.444917,2020,5,12,0,1,38,night
pavel,2020-05-12 00:01:55.395042,2020,5,12,0,1,55,night
...,...,...,...,...,...,...,...,...
artem,2020-05-21 23:49:22.386789,2020,5,21,23,49,22,evening
anatoliy,2020-05-09 23:53:55.599821,2020,5,9,23,53,55,evening
pavel,2020-05-09 23:54:54.260791,2020,5,9,23,54,54,evening
valentina,2020-05-14 23:58:56.754866,2020,5,14,23,58,56,evening
alexander,2020-05-14 23:59:38.758438,2020,5,14,23,59,38,evening

5. Calculate the minimum and maximum for the hours and the mode for the daytime categories.
   - Calculate the maximum hour for the rows where the time of day is night.
   - Calculate the minimum hour for rows where the time of day is morning.
   - In addition, find out who visited the page during those hours and provide one example.
   - Calculate the mode for the hour and daytime.

In [18]:
condition = views['daytime']=='night'
filtred_views = views[condition]
filtred_views['hour'].max()

np.int32(3)

In [25]:
condition2=views['daytime']=='morning'
new_views=views[condition2]
new_views['hour'].min()

np.int32(8)

In [31]:
min_hour=views[views['daytime']=='morning']['hour'].min()
n_views=views[(views['daytime']=='morning') & (views['hour']==min_hour)]
exm=n_views.index[0]
exm.title()

'Alexander'

In [39]:
print(f"The mode for the column 'hour' is {views['hour'].mode()[0]}\n")
print(f"The mode for the column 'daytime' is {views['daytime'].mode()[0]}")

The mode for the column 'hour' is 22

The mode for the column 'daytime' is evening

6. Show the three earliest and latest hours of the day and their corresponding usernames using `nsmallest()` and `nlargest()`.

In [40]:
views['hour'].nsmallest(3)

user
artem         0
konstantin    0
konstantin    0
Name: hour, dtype: int32

In [42]:
views['hour'].nlargest(3)

user
konstantin    23
artem         23
artem         23
Name: hour, dtype: int32

7. Use the `describe()` method to get the basic statistics for the columns.
   - To find the most popular visiting interval, calculate the interquartile range for the hour by extracting values from the result of the `describe()` method and storing them in the variable `iqr`.

In [50]:
statics=views['hour'].describe()
statics
q3=statics['75%']
q1=statics['25%']
iqr=q3-q1
iqr

np.float64(9.0)

In [51]:
views.describe()

,datetime,year,month,day,hour,minute,second
count,1076,1076.0,1076.000000,1076.000000,1076.000000,1076.000000,1076.000000
mean,2020-05-10 09:00:41.211420672,2020.0,4.870818,13.552974,16.249071,29.629182,29.500929
min,2020-04-17 12:01:08.463179,2020.0,4.000000,1.000000,0.000000,0.000000,0.000000
25%,2020-05-10 01:13:49.857472,2020.0,5.000000,11.000000,13.000000,14.000000,14.000000
50%,2020-05-11 22:48:35.302552832,2020.0,5.000000,13.000000,19.000000,29.000000,30.000000
75%,2020-05-14 14:44:34.749530624,2020.0,5.000000,15.000000,22.000000,46.000000,45.000000
max,2020-05-22 10:36:14.662600,2020.0,5.000000,30.000000,23.000000,59.000000,59.000000
std,NaN,0.0,0.335557,4.906567,6.955490,17.689388,17.405506