# Exercise 02

1. [Download](https://drive.google.com/open?id=1kFMUiXtrlw5B6WTjJ-mUm4-STV28Zsvn) and read the CSV file, making `ID` the index column.

In [ ]:
import pandas as pd
auto_df=pd.read_csv("../data/auto.csv")
auto_df.set_index('ID', inplace=True)
auto_df

        CarNumber    Make_n_model  Refund    Fines  History
ID
0    Y163O8161RUS      Ford Focus     2.0   3200.0      NaN
1     E432XX77RUS    Toyota Camry     1.0   6500.0      NaN
2     7184TT36RUS      Ford Focus     1.0   2100.0      NaN
3    X582HE161RUS      Ford Focus     2.0   2000.0      NaN
4    E34877152RUS      Ford Focus     2.0   6100.0      NaN
..            ...             ...     ...      ...      ...
926  Y163O8161RUS      Ford Focus     2.0   1600.0      NaN
927  M0309X197RUS      Ford Focus     1.0  22300.0      NaN
928  O673E8197RUS      Ford Focus     2.0    600.0      NaN
929  8610T8154RUS      Ford Focus     1.0   2000.0      NaN
930  H419XE197RUS  Toyota Corolla     2.0      NaN      2.0

[931 rows x 5 columns]

2. Count the number of observations using the method `count()`.

In [83]:
auto_df.count()

CarNumber       931
Make_n_model    931
Refund          914
Fines           869
History          82
dtype: int64

3. Drop the duplicates, taking into account only the following columns: `CarNumber`, `Make_n_Model`, and `Fines`.

In [84]:
auto_df_no_dupl=auto_df.drop_duplicates(subset=['CarNumber','Make_n_model', 'Fines'],keep='last' )
auto_df_no_dupl

        CarNumber    Make_n_model  Refund    Fines  History
ID
0    Y163O8161RUS      Ford Focus     2.0   3200.0      NaN
1     E432XX77RUS    Toyota Camry     1.0   6500.0      NaN
2     7184TT36RUS      Ford Focus     1.0   2100.0      NaN
3    X582HE161RUS      Ford Focus     2.0   2000.0      NaN
5    92918M178RUS      Ford Focus     1.0   5700.0      NaN
..            ...             ...     ...      ...      ...
926  Y163O8161RUS      Ford Focus     2.0   1600.0      NaN
927  M0309X197RUS      Ford Focus     1.0  22300.0      NaN
928  O673E8197RUS      Ford Focus     2.0    600.0      NaN
929  8610T8154RUS      Ford Focus     1.0   2000.0      NaN
930  H419XE197RUS  Toyota Corolla     2.0      NaN      2.0

[725 rows x 5 columns]

In [85]:
auto_df_no_dupl.count()

CarNumber       725
Make_n_model    725
Refund          713
Fines           665
History          65
dtype: int64

4. Work with missing values.
   - Check how many values are missing from each column.
   - Drop all columns with over 500 missing values using the argument `thresh`. Check how many missing values are in each column.
   - Replace all the missing values in the `Refund` column with the previous value in that column for that cell. Use the argument method and check how many values are missing from each column.
   - Replace all the missing values in the `Fines` column with the mean value of this column (excluding NA/NULL values when computing the mean). Check how many values are missing from each column.

In [86]:
auto_df.isnull().sum()

CarNumber         0
Make_n_model      0
Refund           17
Fines            62
History         849
dtype: int64

In [87]:
auto_df_clean=auto_df.dropna(axis=1, thresh=len(auto_df)-500)
auto_df_clean

        CarNumber    Make_n_model  Refund    Fines
ID
0    Y163O8161RUS      Ford Focus     2.0   3200.0
1     E432XX77RUS    Toyota Camry     1.0   6500.0
2     7184TT36RUS      Ford Focus     1.0   2100.0
3    X582HE161RUS      Ford Focus     2.0   2000.0
4    E34877152RUS      Ford Focus     2.0   6100.0
..            ...             ...     ...      ...
926  Y163O8161RUS      Ford Focus     2.0   1600.0
927  M0309X197RUS      Ford Focus     1.0  22300.0
928  O673E8197RUS      Ford Focus     2.0    600.0
929  8610T8154RUS      Ford Focus     1.0   2000.0
930  H419XE197RUS  Toyota Corolla     2.0      NaN

[931 rows x 4 columns]

In [88]:
auto_df_clean['Refund'].ffill(inplace=True)
auto_df_clean

/tmp/ipykernel_307550/3951543253.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  auto_df_clean['Refund'].ffill(inplace=True)
/tmp/ipykernel_307550/3951543253.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  auto_df_clean['Refund'].ffill(inplace=True)

        CarNumber    Make_n_model  Refund    Fines
ID
0    Y163O8161RUS      Ford Focus     2.0   3200.0
1     E432XX77RUS    Toyota Camry     1.0   6500.0
2     7184TT36RUS      Ford Focus     1.0   2100.0
3    X582HE161RUS      Ford Focus     2.0   2000.0
4    E34877152RUS      Ford Focus     2.0   6100.0
..            ...             ...     ...      ...
926  Y163O8161RUS      Ford Focus     2.0   1600.0
927  M0309X197RUS      Ford Focus     1.0  22300.0
928  O673E8197RUS      Ford Focus     2.0    600.0
929  8610T8154RUS      Ford Focus     1.0   2000.0
930  H419XE197RUS  Toyota Corolla     2.0      NaN

[931 rows x 4 columns]

In [89]:
auto_df_clean['Fines'].fillna(auto_df_clean['Fines'].mean(),inplace=True)
auto_df_clean

/tmp/ipykernel_307550/2109348609.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  auto_df_clean['Fines'].fillna(auto_df_clean['Fines'].mean(),inplace=True)
/tmp/ipykernel_307550/2109348609.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  auto_df_clean['Fines'].fillna(auto_df_clean['Fines'].mean(),inplace=True)

        CarNumber    Make_n_model  Refund         Fines
ID
0    Y163O8161RUS      Ford Focus     2.0   3200.000000
1     E432XX77RUS    Toyota Camry     1.0   6500.000000
2     7184TT36RUS      Ford Focus     1.0   2100.000000
3    X582HE161RUS      Ford Focus     2.0   2000.000000
4    E34877152RUS      Ford Focus     2.0   6100.000000
..            ...             ...     ...           ...
926  Y163O8161RUS      Ford Focus     2.0   1600.000000
927  M0309X197RUS      Ford Focus     1.0  22300.000000
928  O673E8197RUS      Ford Focus     2.0    600.000000
929  8610T8154RUS      Ford Focus     1.0   2000.000000
930  H419XE197RUS  Toyota Corolla     2.0   7860.989643

[931 rows x 4 columns]

5. Split and parse the make and model.
   - Use the apply method for both splitting and extracting values to the new columns, `Make` and `Model`.
   - Drop the column `Make_n_Model`.
   - Save the dataframe in the `auto.json` JSON file in the format below:
    ```
    [{"CarNumber":"Y163O8161RUS","Refund":2.0,"Fines":3200.0,"Make":"Ford",
    "Model":"Focus"},
    
    {"CarNumber":"E432XX77RUS","Refund":1.0,"Fines":6500.0,"Make":"Toyota",
    "Model":"Camry"}]

In [90]:
def check_len(line):
    parts=line.split(' ', 1)
    if len(parts)>1:
        return parts[1]
    else:
        return None

auto_df_clean['Make']=auto_df_clean['Make_n_model'].apply(lambda x: x.split(' ')[0])
auto_df_clean['Model']=auto_df_clean['Make_n_model'].apply(check_len)
auto_df_clean.drop(columns=['Make_n_model'], inplace = True)
auto_df_clean.to_json('auto.json', orient='records', lines=True)
auto_df_clean

        CarNumber  Refund         Fines    Make    Model
ID
0    Y163O8161RUS     2.0   3200.000000    Ford    Focus
1     E432XX77RUS     1.0   6500.000000  Toyota    Camry
2     7184TT36RUS     1.0   2100.000000    Ford    Focus
3    X582HE161RUS     2.0   2000.000000    Ford    Focus
4    E34877152RUS     2.0   6100.000000    Ford    Focus
..            ...     ...           ...     ...      ...
926  Y163O8161RUS     2.0   1600.000000    Ford    Focus
927  M0309X197RUS     1.0  22300.000000    Ford    Focus
928  O673E8197RUS     2.0    600.000000    Ford    Focus
929  8610T8154RUS     1.0   2000.000000    Ford    Focus
930  H419XE197RUS     2.0   7860.989643  Toyota  Corolla

[931 rows x 5 columns]