# Exercise 03

## 1. Load the JSON file that you created in the previous exercise into a dataframe.
   - Set the `CarNumber` column as the index.

In [ ]:
import pandas as pd
df=pd.read_json('../data/auto.json', lines=True)
df.set_index('CarNumber', inplace=True)
df

              Refund         Fines    Make    Model
CarNumber
Y163O8161RUS       2   3200.000000    Ford    Focus
E432XX77RUS        1   6500.000000  Toyota    Camry
7184TT36RUS        1   2100.000000    Ford    Focus
X582HE161RUS       2   2000.000000    Ford    Focus
E34877152RUS       2   6100.000000    Ford    Focus
...              ...           ...     ...      ...
Y163O8161RUS       2   1600.000000    Ford    Focus
M0309X197RUS       1  22300.000000    Ford    Focus
O673E8197RUS       2    600.000000    Ford    Focus
8610T8154RUS       1   2000.000000    Ford    Focus
H419XE197RUS       2   7860.989643  Toyota  Corolla

[931 rows x 4 columns]

## 2. Make the following selections:
   - Display the rows where the fines are greater than 2,100.

In [11]:
cond_for_fines=df['Fines'] > 2100
df_1=df[cond_for_fines]
df_1

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
E432XX77RUS        1   6500.000000      Toyota    Camry
E34877152RUS       2   6100.000000        Ford    Focus
92918M178RUS       1   5700.000000        Ford    Focus
X4128H125RUS       1   7860.989643        Ford    Focus
...              ...           ...         ...      ...
O718MM163RUS       2   7860.989643        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
O22097197RUS       1  24300.000000        Ford    Focus
M0309X197RUS       1  22300.000000        Ford    Focus
H419XE197RUS       2   7860.989643      Toyota  Corolla

[562 rows x 4 columns]

  - Display the rows where the fines are greater than 2,100 and the refund equals 2.

In [18]:
df_2=df[(df['Fines']>2100) & (df['Refund']==2)]
df_2

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
E34877152RUS       2   6100.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
707987163RUS       2   2200.000000        Ford    Focus
K330T8197RUS       2   8200.000000       Skoda  Octavia
...              ...           ...         ...      ...
O136HO197RUS       2   7800.000000      Toyota  Corolla
O68897197RUS       2  12300.000000        Ford    Focus
O718MM163RUS       2   7860.989643        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
H419XE197RUS       2   7860.989643      Toyota  Corolla

[382 rows x 4 columns]

 - Display the rows where the models are from the list: `[’Focus’, ’Corolla’]`.

In [24]:
df_3=df[df['Model'].isin(['Focus', 'Corolla'])]
df_3

              Refund         Fines    Make    Model
CarNumber
Y163O8161RUS       2   3200.000000    Ford    Focus
7184TT36RUS        1   2100.000000    Ford    Focus
X582HE161RUS       2   2000.000000    Ford    Focus
E34877152RUS       2   6100.000000    Ford    Focus
92918M178RUS       1   5700.000000    Ford    Focus
...              ...           ...     ...      ...
Y163O8161RUS       2   1600.000000    Ford    Focus
M0309X197RUS       1  22300.000000    Ford    Focus
O673E8197RUS       2    600.000000    Ford    Focus
8610T8154RUS       1   2000.000000    Ford    Focus
H419XE197RUS       2   7860.989643  Toyota  Corolla

[763 rows x 4 columns]

- Display the rows where the car number is from the list: `[’Y7689C197RUS’, ’92928M178RUS’, ’7788KT197RUS’, ’H115YO163RUS’, ’X758HY197RUS’]`.

In [25]:
df_4=df[df.index.isin( ['Y7689C197RUS', '92928M178RUS', '7788KT197RUS', 'H115YO163RUS', 'X758HY197RUS'])]
df_4

              Refund          Fines  Make  Model
CarNumber
92928M178RUS       1    7860.989643  Ford  Focus
H115YO163RUS       1    2200.000000  Ford  Focus
92928M178RUS       2    1200.000000  Ford  Focus
7788KT197RUS       2   12000.000000  Ford  Focus
X758HY197RUS       2   24200.000000  Ford  Focus
X758HY197RUS       2   72600.000000  Ford  Focus
Y7689C197RUS       1   27000.000000  Ford  Focus
92928M178RUS       1     600.000000  Ford  Focus
H115YO163RUS       1    7860.989643  Ford  Focus
H115YO163RUS       2    1100.000000  Ford  Focus
7788KT197RUS       2    7860.989643  Ford  Focus
7788KT197RUS       1   20000.000000  Ford  Focus
X758HY197RUS       2  145200.000000  Ford  Focus
92928M178RUS       1    1200.000000  Ford  Focus
Y7689C197RUS       2    9000.000000  Ford  Focus
Y7689C197RUS       2   45000.000000  Ford  Focus
7788KT197RUS       2    4000.000000  Ford  Focus
Y7689C197RUS       1   36000.000000  Ford  Focus
92928M178RUS       2    3000.000000  Ford  Focus

## 3. Make the aggregations with the `make` and `model`.
   - Display the median fines grouped by `make`.

In [53]:
df_group_by_make=df.groupby('Make')['Fines'].agg(["median"])
df_group_by_make

            median
Make
Audi        4200.0
BMW         3000.0
Ford        3000.0
Skoda       3000.0
Toyota      7350.0
Volkswagen  4300.0
Volvo       6800.0

- Display the median fines grouped by `make` and `model`.

In [52]:
df_group_by_make_model=df.groupby(['Make', 'Model'])['Fines'].agg(['median'])
df_group_by_make_model

                    median
Make       Model
Ford       Focus    3000.0
           Mondeo   6700.0
Skoda      Octavia  3000.0
Toyota     Camry    7200.0
           Corolla  7700.0
Volkswagen Golf     5000.0
           Jetta    2800.0
           Passat   3100.0
           Touareg  5800.0

- Display the number of fines grouped by `make` and `model` to understand if we can trust the median values.

In [51]:
df_check_median=df.groupby(['Make', 'Model'])['Fines'].agg(['count'])
df_check_median

                    count
Make       Model
Ford       Focus      743
           Mondeo      11
Skoda      Octavia     60
Toyota     Camry       20
           Corolla     20
Volkswagen Golf        25
           Jetta        8
           Passat      26
           Touareg      6

- Display the minimum and maximum fines grouped by `make` and `model` to better understand the variance.

In [47]:
min_and_max_df=df.groupby(['Make', 'Model'])['Fines'].agg(['min', 'max'])
min_and_max_df

                       min            max
Make       Model
Ford       Focus     100.0  180000.000000
           Mondeo   1100.0   46200.000000
Skoda      Octavia   300.0  145000.000000
Toyota     Camry     500.0   22400.000000
           Corolla   900.0   34300.000000
Volkswagen Golf      200.0  168000.000000
           Jetta     500.0   46000.000000
           Passat    100.0   29700.000000
           Touareg   500.0    7860.989643

 - Display the standard deviation of fines grouped by `make` and `model` to better understand the variance.

In [50]:
std_df=df.groupby(['Make', 'Model'])['Fines'].agg(['std'])
std_df

                             std
Make       Model
Ford       Focus    13680.918377
           Mondeo   15996.084748
Skoda      Octavia  22016.695805
Toyota     Camry     6146.415086
           Corolla   9408.880792
Volkswagen Golf     33272.925929
           Jetta    15450.421862
           Passat    6700.834922
           Touareg   2969.976425

## 4. Make aggregations with car numbers.
   - Display the car numbers, grouped by the number of fines in descending order. We want to find those who most often violated the law.

In [66]:
numbs=df.index.value_counts()
df_new=numbs.groupby(numbs).apply(lambda x: x.index.tolist())
res=df_new.sort_index(ascending=False)
res

count
5    [9499KX178RUS, Y358O8197RUS, 7784KT197RUS, 929...
4    [M375CH197RUS, 96429X178RUS, X765HY197RUS, 736...
3    [9677MO178RUS, 83218C154RUS, Y7719C197RUS, O13...
2    [7065C8197RUS, 9941KK197RUS, Y8259C197RUS, H88...
1    [O673E8197RUS, X582HE161RUS, H234YH197RUS, K33...
Name: count, dtype: object

- Select from the initial dataframe all the rows corresponding to the top-1 car number. We want to zoom in a little bit.

In [68]:
top_fine_car=df.index.value_counts().index[0]
top_one_car=df.loc[top_fine_car]
top_one_car

              Refund   Fines  Make  Model
CarNumber
9499KX178RUS       2  2300.0  Ford  Focus
9499KX178RUS       2  2300.0  Ford  Focus
9499KX178RUS       2  2300.0  Ford  Focus
9499KX178RUS       1  2300.0  Ford  Focus
9499KX178RUS       1  4600.0  Ford  Focus

- Display the car numbers grouped by sum of fines in descending order. We want to find those who paid the most.

In [75]:
paid_the_most=df.groupby('CarNumber')['Fines'].sum().sort_values(ascending=False)
paid_the_most

CarNumber
M0279X197RUS    252000.0
X758HY197RUS    242000.0
9020YC197RUS    217500.0
Y352O8197RUS    207200.0
Y778EE197RUS    192000.0
                  ...
K376HE161RUS       200.0
8182XX154RUS       200.0
705787163RUS       200.0
Y166O8161RUS       100.0
C58078163RUS       100.0
Name: Fines, Length: 531, dtype: float64

- Select all the rows corresponding to the top-1 car number from the initial dataframe. We want to zoom in a little bit.

In [78]:
champion=paid_the_most.index[0]
paid_the_most_df=df.loc[champion]
paid_the_most_df

              Refund     Fines  Make  Model
CarNumber
M0279X197RUS       2  180000.0  Ford  Focus
M0279X197RUS       1   36000.0  Ford  Focus
M0279X197RUS       2   36000.0  Ford  Focus

- Display a table that answers the question, "Are there any car numbers connected to different models?"

In [ ]:
car_numb=df.groupby('CarNumber')
count_uniq=car_numb['Model'].nunique()
cond=count_uniq>1
res_df=count_uniq[cond]
#res_df