# Exercise 04.  Enrichment and transformations

## 1. Read the JSON file that you saved in ex02.
   - One of the columns is a float, so let's define its format in Pandas using `pd.options.display.float_format`: floats should be displayed with two decimals.

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_json('../data/auto.json', lines=True)
pd.options.display.float_format='{:.2f}'.format
df

        CarNumber  Refund    Fines    Make    Model
0    Y163O8161RUS       2  3200.00    Ford    Focus
1     E432XX77RUS       1  6500.00  Toyota    Camry
2     7184TT36RUS       1  2100.00    Ford    Focus
3    X582HE161RUS       2  2000.00    Ford    Focus
4    E34877152RUS       2  6100.00    Ford    Focus
..            ...     ...      ...     ...      ...
926  Y163O8161RUS       2  1600.00    Ford    Focus
927  M0309X197RUS       1 22300.00    Ford    Focus
928  O673E8197RUS       2   600.00    Ford    Focus
929  8610T8154RUS       1  2000.00    Ford    Focus
930  H419XE197RUS       2  7860.99  Toyota  Corolla

[931 rows x 5 columns]

 - There are missing values from the Model; do not do anything with them.

## 2. Enrich the dataframe using a sample from that dataframe.
   - Create a sample with 200 new observations using `random_state = 21`.

- The sample should not contain new combinations of the `car number`, `make`, and `model`, so the entire dataset will be consistent in this regard.
- There are no restrictions on the `refund` and `fines` columns. You can randomly select a value from these columns and apply it to any car number.

In [23]:
no_dupl_df=df.drop_duplicates(subset=['CarNumber', 'Make', 'Model'])
new_sample=no_dupl_df.sample(200, replace= True, random_state=21)
new_sample.loc[:,'Refund']=np.random.randint(1,3, len(new_sample))
new_sample.loc[:,'Fines']=np.random.randint(100,df['Fines'].max()+100, len(new_sample))
concat_rows=pd.concat([df, new_sample],ignore_index=True)
concat_rows

         CarNumber  Refund     Fines        Make   Model
0     Y163O8161RUS       2   3200.00        Ford   Focus
1      E432XX77RUS       1   6500.00      Toyota   Camry
2      7184TT36RUS       1   2100.00        Ford   Focus
3     X582HE161RUS       2   2000.00        Ford   Focus
4     E34877152RUS       2   6100.00        Ford   Focus
...            ...     ...       ...         ...     ...
1126  Y418EX197RUS       2  88540.00  Volkswagen  Passat
1127  O22397197RUS       2  62420.00        Ford   Focus
1128  X582HE161RUS       2 109977.00        Ford   Focus
1129  H907YK197RUS       1 123836.00        Ford   Focus
1130  X765HY197RUS       2  26629.00        Ford   Focus

[1131 rows x 5 columns]

## 3. Enrich the `concat_rows` dataframe with a new column containing generated data.
   - Create a series named "Year" with random integers from 1980 to 2019.
   - Use `np.random.seed(21)` before generating the years.
   - Concatenate the series with the data frame and name it `fines`.

In [30]:
np.random.seed(21)
year_series=np.random.randint(1980,2020,size= len(df))
res_year=pd.Series(year_series, name='Year')
res_year

0      1989
1      1995
2      1984
3      2015
4      2014
       ...
926    1998
927    1987
928    1996
929    2013
930    1994
Name: Year, Length: 931, dtype: int64

In [36]:
df_with_year=pd.concat([df,res_year], axis=1)
df_with_year.rename(columns={'Year': 'fines'}, inplace=True)
df_with_year

        CarNumber  Refund    Fines    Make    Model  fines
0    Y163O8161RUS       2  3200.00    Ford    Focus   1989
1     E432XX77RUS       1  6500.00  Toyota    Camry   1995
2     7184TT36RUS       1  2100.00    Ford    Focus   1984
3    X582HE161RUS       2  2000.00    Ford    Focus   2015
4    E34877152RUS       2  6100.00    Ford    Focus   2014
..            ...     ...      ...     ...      ...    ...
926  Y163O8161RUS       2  1600.00    Ford    Focus   1998
927  M0309X197RUS       1 22300.00    Ford    Focus   1987
928  O673E8197RUS       2   600.00    Ford    Focus   1996
929  8610T8154RUS       1  2000.00    Ford    Focus   2013
930  H419XE197RUS       2  7860.99  Toyota  Corolla   1994

[931 rows x 6 columns]

## 4. Enrich the dataframe with data from another dataframe.
   - Create a new dataframe with car numbers and their owners.
      - Get the most popular surnames in the US (you can find the file [surname.json]
      - Create a new series with the surnames. They should not contain special characters, such as commas or brackets. The count should equal the number of unique car numbers in the sample (use `random_state = 21`).
      - Create the dataframe `owners` with two columns: `CarNumber` and `SURNAME`.

In [ ]:
df_from_sur=pd.read_json('../data/surname.json')
df_from_sur.columns=df_from_sur.iloc[0]
df_from_sur=df_from_sur[1:].reset_index(drop=True)
surnames=pd.Series(df_from_sur['NAME'])
uniq_nums=df['CarNumber'].nunique()
sample_sur=surnames.sample(uniq_nums,replace=True, random_state=21)
sample_sur.reset_index(drop=True, inplace=True)
owners=pd.DataFrame({'CarNumber': df['CarNumber'].unique(),
                    'Names': sample_sur})
owners

        CarNumber       Names
0    Y163O8161RUS  RICHARDSON
1     E432XX77RUS        ROSS
2     7184TT36RUS      MORGAN
3    X582HE161RUS      BAILEY
4    E34877152RUS       LOPEZ
..            ...         ...
526  7367C8197RUS    CAMPBELL
527  9398MM199RUS        HALL
528  O136HO197RUS       BAKER
529  M0309X197RUS        DIAZ
530  O673E8197RUS      MORGAN

[531 rows x 2 columns]

- Append five more observations to the `fines` dataframe. Come up with your own ideas for `CarNumber`, etc.
- Delete the last 20 observations from the `owners` dataframe and add three new observations that are not the same as those added to the `fines` dataframe.

In [94]:
new_fines_data = [
    # Строка 1
    {'CarNumber': 'A001AA99RUS', 'Make': 'Tesla', 'Model': 'Model S', 
     'Fines': 1500.0, 'Refund': 2.0, 'fines': 2021},
    
    # Строка 2
    {'CarNumber': 'B002BB77RUS', 'Make': 'Kia', 'Model': 'Rio', 
     'Fines': 500.0, 'Refund': 1.0, 'fines': 2019},
    
    # Строка 3
    {'CarNumber': 'C003CC152RUS', 'Make': 'Haval', 'Model': 'Jolion', 
     'Fines': 2500.0, 'Refund': 2.0, 'fines': 2022},
    
    # Строка 4
    {'CarNumber': 'D004DD50RUS', 'Make': 'Geely', 'Model': 'Coolray', 
     'Fines': 1000.0, 'Refund': 1.0, 'fines': 2023},
    
    # Строка 5
    {'CarNumber': 'E005EE178RUS', 'Make': 'Lada', 'Model': 'Vesta', 
     'Fines': 5000.0, 'Refund': 2.0, 'fines': 2020}
]

new_fines_df = pd.DataFrame(new_fines_data)
df_res_20=pd.concat([df_with_year, new_fines_df], ignore_index=True)
df_res_20

        CarNumber  Refund   Fines    Make    Model  fines
0    Y163O8161RUS    2.00 3200.00    Ford    Focus   1989
1     E432XX77RUS    1.00 6500.00  Toyota    Camry   1995
2     7184TT36RUS    1.00 2100.00    Ford    Focus   1984
3    X582HE161RUS    2.00 2000.00    Ford    Focus   2015
4    E34877152RUS    2.00 6100.00    Ford    Focus   2014
..            ...     ...     ...     ...      ...    ...
931   A001AA99RUS    2.00 1500.00   Tesla  Model S   2021
932   B002BB77RUS    1.00  500.00     Kia      Rio   2019
933  C003CC152RUS    2.00 2500.00   Haval   Jolion   2022
934   D004DD50RUS    1.00 1000.00   Geely  Coolray   2023
935  E005EE178RUS    2.00 5000.00    Lada    Vesta   2020

[936 rows x 6 columns]

In [78]:
owner_less_20=owners.drop(owners.index[-20:])
new_owners_data = [
    {'CarNumber': 'X999XX99RUS', 'Names': 'IVANOV'},
    {'CarNumber': 'Y888YY88RUS', 'Names': 'PETROV'},
    {'CarNumber': 'Z777ZZ77RUS', 'Names': 'SIDOROV'}
]
new_owners_df = pd.DataFrame(new_owners_data)
owners_with_3=pd.concat([owner_less_20,new_owners_df], ignore_index=True)
owners_with_3

        CarNumber       Names
0    Y163O8161RUS  RICHARDSON
1     E432XX77RUS        ROSS
2     7184TT36RUS      MORGAN
3    X582HE161RUS      BAILEY
4    E34877152RUS       LOPEZ
..            ...         ...
509  7360C8197RUS      WRIGHT
510  E29677161RUS        HILL
511   X999XX99RUS      IVANOV
512   Y888YY88RUS      PETROV
513   Z777ZZ77RUS     SIDOROV

[514 rows x 2 columns]

- Join the two dataframes.
     - The new dataframe should contain **only** the car numbers that exist in **both** dataframes.

In [95]:
res1=pd.merge(df_res_20, owners_with_3, on='CarNumber', how='inner')
res1

        CarNumber  Refund    Fines        Make    Model  fines       Names
0    Y163O8161RUS    2.00  3200.00        Ford    Focus   1989  RICHARDSON
1     E432XX77RUS    1.00  6500.00      Toyota    Camry   1995        ROSS
2     7184TT36RUS    1.00  2100.00        Ford    Focus   1984      MORGAN
3    X582HE161RUS    2.00  2000.00        Ford    Focus   2015      BAILEY
4    E34877152RUS    2.00  6100.00        Ford    Focus   2014       LOPEZ
..            ...     ...      ...         ...      ...    ...         ...
904  7065C8197RUS    2.00 11400.00  Volkswagen   Passat   1997      FOSTER
905  O22097197RUS    1.00 24300.00        Ford    Focus   1985       SMITH
906  Y163O8161RUS    2.00  1600.00        Ford    Focus   1998  RICHARDSON
907  8610T8154RUS    1.00  2000.00        Ford    Focus   2013    THOMPSON
908  H419XE197RUS    2.00  7860.99      Toyota  Corolla   1994     ALVAREZ

[909 rows x 7 columns]

- The new dataframe should contain **all** the car numbers from **both** dataframes.

In [96]:
res2=pd.merge(df_res_20, owners_with_3, on='CarNumber', how='outer')
res2

        CarNumber  Refund    Fines  Make  Model   fines    Names
0    704687163RUS    2.00  1400.00  Ford  Focus 2005.00  ROBERTS
1    704787163RUS    2.00  2800.00  Ford  Focus 2018.00   FOSTER
2    704987163RUS    2.00  7860.99  Ford  Focus 1983.00  ROBERTS
3    705287163RUS    2.00  2000.00  Ford  Focus 1982.00   HARRIS
4    705387163RUS    2.00   700.00  Ford  Focus 1985.00   MARTIN
..            ...     ...      ...   ...    ...     ...      ...
934  Y969O8197RUS    2.00  7800.00  Ford  Focus 1998.00     ROSS
935  Y973O8197RUS    2.00  7860.99  Ford  Focus 1981.00   GARCIA
936  Y973O8197RUS    1.00 34800.00  Ford  Focus 1995.00   GARCIA
937  Y973O8197RUS    1.00 69600.00  Ford  Focus 1992.00   GARCIA
938   Z777ZZ77RUS     NaN      NaN   NaN    NaN     NaN  SIDOROV

[939 rows x 7 columns]

- The new dataframe should contain **only** the car numbers from the `fines` dataframe.

In [97]:
res3=pd.merge(df_res_20, owners_with_3, on='CarNumber', how='left')
res3

        CarNumber  Refund   Fines    Make    Model  fines       Names
0    Y163O8161RUS    2.00 3200.00    Ford    Focus   1989  RICHARDSON
1     E432XX77RUS    1.00 6500.00  Toyota    Camry   1995        ROSS
2     7184TT36RUS    1.00 2100.00    Ford    Focus   1984      MORGAN
3    X582HE161RUS    2.00 2000.00    Ford    Focus   2015      BAILEY
4    E34877152RUS    2.00 6100.00    Ford    Focus   2014       LOPEZ
..            ...     ...     ...     ...      ...    ...         ...
931   A001AA99RUS    2.00 1500.00   Tesla  Model S   2021         NaN
932   B002BB77RUS    1.00  500.00     Kia      Rio   2019         NaN
933  C003CC152RUS    2.00 2500.00   Haval   Jolion   2022         NaN
934   D004DD50RUS    1.00 1000.00   Geely  Coolray   2023         NaN
935  E005EE178RUS    2.00 5000.00    Lada    Vesta   2020         NaN

[936 rows x 7 columns]

- The new dataframe should contain **only** the car numbers from the `owners` dataframe.

In [98]:
res4=pd.merge( df_res_20,owners_with_3, on='CarNumber', how='right')
res4

        CarNumber  Refund    Fines    Make  Model   fines       Names
0    Y163O8161RUS    2.00  3200.00    Ford  Focus 1989.00  RICHARDSON
1    Y163O8161RUS    2.00  1600.00    Ford  Focus 1998.00  RICHARDSON
2     E432XX77RUS    1.00  6500.00  Toyota  Camry 1995.00        ROSS
3     E432XX77RUS    2.00 13000.00  Toyota  Camry 2013.00        ROSS
4     7184TT36RUS    1.00  2100.00    Ford  Focus 1984.00      MORGAN
..            ...     ...      ...     ...    ...     ...         ...
907  7360C8197RUS    2.00  9600.00    Ford  Focus 1994.00      WRIGHT
908  E29677161RUS    2.00  6000.00    Ford  Focus 2017.00        HILL
909   X999XX99RUS     NaN      NaN     NaN    NaN     NaN      IVANOV
910   Y888YY88RUS     NaN      NaN     NaN    NaN     NaN      PETROV
911   Z777ZZ77RUS     NaN      NaN     NaN    NaN     NaN     SIDOROV

[912 rows x 7 columns]

## 5. Create a pivot table from the `fines` dataframe. It should look like this (the values are the sums of the fines), but with all the years. The values may be different for you.

In [99]:
my_pivot_table=res2.pivot_table(index=['Make', 'Model'],columns='fines',values='Fines', aggfunc='sum' )
my_pivot_table

fines               1980.00   1981.00   1982.00   1983.00  1984.00   1985.00  \
Make       Model
Ford       Focus   86260.99 295921.98 100600.00 132660.99 55482.97 177421.98
           Mondeo       NaN   1100.00       NaN       NaN      NaN       NaN
Geely      Coolray      NaN       NaN       NaN       NaN      NaN       NaN
Haval      Jolion       NaN       NaN       NaN       NaN      NaN       NaN
Kia        Rio          NaN       NaN       NaN       NaN      NaN       NaN
Lada       Vesta        NaN       NaN       NaN       NaN      NaN       NaN
Skoda      Octavia      NaN  14300.00   7860.99       NaN      NaN 192300.00
Tesla      Model S      NaN       NaN       NaN       NaN      NaN       NaN
Toyota     Camry    8860.99   4400.00   4400.00       NaN      NaN   7860.99
           Corolla 26000.00       NaN       NaN       NaN      NaN  32300.00
Volkswagen Golf         NaN       NaN       NaN       NaN      NaN   4100.00
           Jetta        NaN       NaN   1600.00       NaN  9000.00       NaN
           Passat       NaN   4500.00       NaN       NaN  6200.00       NaN
           Touareg      NaN       NaN   6300.00       NaN      NaN       NaN

fines               1986.00   1987.00   1988.00   1989.00  ...   2014.00  \
Make       Model                                           ...
Ford       Focus   61021.98 192182.97 105660.99 116500.00  ... 173000.00
           Mondeo       NaN       NaN       NaN       NaN  ...       NaN
Geely      Coolray      NaN       NaN       NaN       NaN  ...       NaN
Haval      Jolion       NaN       NaN       NaN       NaN  ...       NaN
Kia        Rio          NaN       NaN       NaN       NaN  ...       NaN
Lada       Vesta        NaN       NaN       NaN       NaN  ...       NaN
Skoda      Octavia      NaN   1000.00       NaN   3100.00  ...   9160.99
Tesla      Model S      NaN       NaN       NaN       NaN  ...       NaN
Toyota     Camry        NaN  12800.00       NaN   1000.00  ...       NaN
           Corolla      NaN       NaN   6800.00       NaN  ...       NaN
Volkswagen Golf         NaN       NaN       NaN  10600.00  ...    300.00
           Jetta        NaN       NaN       NaN       NaN  ...       NaN
           Passat       NaN       NaN       NaN       NaN  ...    100.00
           Touareg      NaN       NaN   1300.00       NaN  ...       NaN

fines                2015.00   2016.00   2017.00   2018.00  2019.00  2020.00  \
Make       Model
Ford       Focus   174260.99 104821.98 141221.98 100960.99 87660.99      NaN
           Mondeo   34400.00   8600.00       NaN       NaN      NaN      NaN
Geely      Coolray       NaN       NaN       NaN       NaN      NaN      NaN
Haval      Jolion        NaN       NaN       NaN       NaN      NaN      NaN
Kia        Rio           NaN       NaN       NaN       NaN   500.00      NaN
Lada       Vesta         NaN       NaN       NaN       NaN      NaN  5000.00
Skoda      Octavia    500.00   3000.00   2400.00   9200.00 25000.00      NaN
Tesla      Model S       NaN       NaN       NaN       NaN      NaN      NaN
Toyota     Camry         NaN       NaN       NaN  14400.00      NaN      NaN
           Corolla  24000.00       NaN       NaN  16000.00      NaN      NaN
Volkswagen Golf      5000.00       NaN  10900.00       NaN      NaN      NaN
           Jetta         NaN       NaN       NaN       NaN      NaN      NaN
           Passat   30700.00       NaN    100.00       NaN  9900.00      NaN
           Touareg       NaN       NaN       NaN       NaN      NaN      NaN

fines               2021.00  2022.00  2023.00
Make       Model
Ford       Focus        NaN      NaN      NaN
           Mondeo       NaN      NaN      NaN
Geely      Coolray      NaN      NaN  1000.00
Haval      Jolion       NaN  2500.00      NaN
Kia        Rio          NaN      NaN      NaN
Lada       Vesta        NaN      NaN      NaN
Skoda      Octavia      NaN      NaN      NaN
Tesla      Model S  1500.00      NaN      NaN
Toyota     Camry        NaN      NaN      NaN
           Corolla      NaN      NaN      NaN
Volkswagen Golf         NaN      NaN      NaN
           Jetta        NaN      NaN      NaN
           Passat       NaN      NaN      NaN
           Touareg      NaN      NaN      NaN

[14 rows x 44 columns]

## 6. Save both the `fines` and `owners` dataframes to CSV files without an index.

In [ ]:
owners_with_3.to_csv("../data/owners.csv", index=False)

In [ ]:
df_res_20.to_csv("../data/fines.csv", index=False)